#ifndef __FTN_LIB_ERROR_CODES_FILE_H__
#define __FTN_LIB_ERROR_CODES_FILE_H__

#define UNUSED_PARAM(x) ((void)(x))

#define FTN_SUCCESS(ret_val) ((ret_val) == FTN_ERROR_SUCCESS)

typedef enum FTN_RET_VAL
{
	FTN_ERROR_SUCCESS = 0,
	
	FTN_ERROR_UNKNONE,
	FTN_ERROR_NOT_IMPLEMENTED,
	FTN_ERROR_ARGUMENTS_ERROR,
	FTN_ERROR_INPUT_DATA_BUFFER_IS_TO_SMALL,
	//TODO: add yours error codes here
} FTN_RET_VAL;


#endif